version: '3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: ricardo/nginx:prod
    container_name: nginx
    networks:
      - node-networks
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    build: 
      context: node
      dockerfile: Dockerfile
    image: ricardo/nodeapp
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh node index.js
    tty: true
    volumes:
      - ./node/app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - node-networks
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: "always"
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-networks


networks:
  node-networks:
    driver: bridge