version: '3'

services:
  app:
    build: 
      context: node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    tty: true
    volumes:
      - ./node/app:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - node-networks
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: "always"
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-networks


networks:
  node-networks:
    driver: bridge